# Site settings
title: A blog about code stuff
description: A blog about what I get up to in my spare time.
#baseurl: "/githubPage" # the subpath of your site, e.g. /blog
#url: "https://thatrandomcodernz.github.io/githubPage" 
# User settings
username: Ethan Mitchell
user_description: "I'm a Software Engineer currently based in Auckland, New Zealand. I'm always down to 
learn something new and make cool stuff. If I'm not coding you'll probably find me reading, learning a foreign language, 
or spending far too long in the kitchen being fussy over how thin I'm slicing my onions."
user_title: Software Engineer
email: ethan.en.mitchell@gmail.com
linkedin_username: Ethan Mitchell
github_username:  ThatRandomCoderNZ



collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
