# Site settings
title: A blog about good code
description: A blog about my projects and accomplishments
baseurl: "/githubPage/" # the subpath of your site, e.g. /blog
url: "https://thatrandomcodernz.github.io/githubPage/" 
# User settings
username: Ethan Mitchell
user_description: I am an experienced Software Developer with a passion for creating high quality software.
user_title: Software Developer
email: ethan.en.mitchell@gmail.com
linkedin_username: Ethan Mitchell
github_username:  ThatRandomCoderNZ



collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
